version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit_db
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:14-alpine
    container_name: shareit_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
