DROP TABLE IF EXISTS users, items, requests, bookings, comments, item_requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(70) NOT NULL,
	email varchar(70) NOT NULL,
	CONSTRAINT email_unique UNIQUE (email),
	CONSTRAINT user_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS item_requests (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(300) NOT NULL,
	created timestamp NOT NULL,
	owner_id bigint NOT NULL,
	CONSTRAINT item_request_pk PRIMARY KEY (id),
	CONSTRAINT request_owner_fk FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE restrict
);

CREATE TABLE IF NOT EXISTS items (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	owner_id bigint NOT NULL,
	name varchar(70) NOT NULL,
	description varchar(300) NOT NULL,
	is_available bool NULL,
	request_id bigint,
	CONSTRAINT item_pk PRIMARY KEY (id),
	CONSTRAINT item_owner_fk FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE restrict,
	CONSTRAINT item_request_fk FOREIGN KEY (request_id) REFERENCES public.item_requests(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS bookings (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	starting timestamp NOT NULL,
	ending timestamp NOT NULL,
	booker_id bigint NOT NULL,
	item_id bigint NOT NULL,
	status smallint NOT NULL,
	CONSTRAINT booking_pk PRIMARY KEY (id),
	CONSTRAINT booking_owner_fk FOREIGN KEY (booker_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE restrict,
	CONSTRAINT booking_item_fk FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS comments (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	author_id bigint NOT NULL,
	item_id bigint NOT NULL,
	comment_text varchar(300) NOT NULL,
	created timestamp NOT NULL,
	CONSTRAINT comment_pk PRIMARY KEY (id),
	CONSTRAINT comment_owner_fk FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE restrict,
	CONSTRAINT comment_item_fk FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);